#!/bin/bash

    # Make a PDF file from PS.
    # NOTE: Remove since cropping was not working.
# ps2pdf -dEPSCrop score.ps score.pdf

    # Make a PDF file with GS.
gs -sOutputFile=score.pdf -dNOPAUSE -dBATCH -g468x612 -r72 -sDEVICE=pdfwrite -dSAFER score.ps
