#!/bin/bash

    # Make a PDF file from PS.
    # NOTE: Remove since cropping was not working.
# ps2pdf -dEPSCrop score.ps score.pdf

    # Make a PDF file with GS.
gs -sOutputFile=angklung.pdf -dNOPAUSE -dBATCH -g936x612 -r72 -sDEVICE=pdfwrite   -dSAFER angklung.ps
gs -sOutputFile=gong.pdf     -dNOPAUSE -dBATCH -g936x612 -r72 -sDEVICE=pdfwrite   -dSAFER gong.ps
